# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-16 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0002_auto_20170116_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(max_length=200)),
                ('pwd', models.CharField(max_length=18)),
            ],
        ),
    ]
